### ISSUE TITLE
Data currently unavailable

### ISSUE THREAD

**Issue by csmontt** [rogerbeecham/od-flowvis-ggplot2#1]
Hello Robert,
I was eager to reproduce your example, but unfortunately some data is not available anymore, these are:

`data <- read_tsv("http://homepages.see.leeds.ac.uk/~georjb/datasets/od_ttw.tsv")
codes <- read_tsv("http://homepages.see.leeds.ac.uk/~georjb/datasets/od_ttw_codes.tsv")`

I searched for it on Google but had no luck, I was wondering if this is an error or if it is definitely gone, therefore no possiblity to reproduce the example.

Best regards,

**Comment by rogerbeecham** [comment]
Thanks for your message and sorry for the late reply.

Yes I somehow at some point removed those files from that directory —
replaced them now so should work. Let me know if any further problems or
if you want any of the code talking through.

Roger

**Comment by csmontt** [comment]
Hello Roger,

Now runs perfectly! thanks.
The only thing is not defined in your code is 'focus_colours', I just omitted that line and it doesn´t seem to make a difference.

Best,
